name: Build and Deploy Docker Image

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timestamp
        run: |
          echo "TIMESTAMP=$(date +%y.%m%d.%H%M)" >> $GITHUB_ENV
          echo "DATESTAMP=$(date +%y.%m%d)" >> $GITHUB_ENV
          echo "MONTHSTAMP=$(date +%y.%m)" >> $GITHUB_ENV

      - name: Build and Push Docker Image to GHCR
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ghcr.io/nakanishi123/discord-python-docker:${{ env.TIMESTAMP }}
            ghcr.io/nakanishi123/discord-python-docker:${{ env.DATESTAMP }}
            ghcr.io/nakanishi123/discord-python-docker:${{ env.MONTHSTAMP }}
            ghcr.io/nakanishi123/discord-python-docker:latest
